/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../app/modules/dialog/module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/common/src/localization';
import * as import6 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import7 from '@angular/forms/src/form_builder';
import * as import8 from '../../../../app/modules/dialog/service';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/i18n/tokens';
class DialogModuleInjector extends import0.NgModuleInjector<import1.DialogModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _ReactiveFormsModule_3:import4.ReactiveFormsModule;
  _DialogModule_4:import1.DialogModule;
  __NgLocalization_5:import5.NgLocaleLocalization;
  __RadioControlRegistry_6:import6.RadioControlRegistry;
  __FormBuilder_7:import7.FormBuilder;
  __DialogService_8:import8.DialogService;
  constructor(parent:import9.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import5.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import5.NgLocaleLocalization(this.parent.get(import10.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _RadioControlRegistry_6():import6.RadioControlRegistry {
    if ((this.__RadioControlRegistry_6 == null)) { (this.__RadioControlRegistry_6 = new import6.RadioControlRegistry()); }
    return this.__RadioControlRegistry_6;
  }
  get _FormBuilder_7():import7.FormBuilder {
    if ((this.__FormBuilder_7 == null)) { (this.__FormBuilder_7 = new import7.FormBuilder()); }
    return this.__FormBuilder_7;
  }
  get _DialogService_8():import8.DialogService {
    if ((this.__DialogService_8 == null)) { (this.__DialogService_8 = new import8.DialogService()); }
    return this.__DialogService_8;
  }
  createInternal():import1.DialogModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._ReactiveFormsModule_3 = new import4.ReactiveFormsModule();
    this._DialogModule_4 = new import1.DialogModule();
    return this._DialogModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import1.DialogModule)) { return this._DialogModule_4; }
    if ((token === import5.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import6.RadioControlRegistry)) { return this._RadioControlRegistry_6; }
    if ((token === import7.FormBuilder)) { return this._FormBuilder_7; }
    if ((token === import8.DialogService)) { return this._DialogService_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DialogModuleNgFactory:import0.NgModuleFactory<import1.DialogModule> = new import0.NgModuleFactory(DialogModuleInjector,import1.DialogModule);