/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/components/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/services/session.service';
import * as import9 from '../../../app/services/log.service';
import * as import10 from '../../../app/components/log.component';
import * as import11 from './log.component.ngfactory';
import * as import12 from '../../../app/modules/building/components/building';
import * as import13 from '../modules/building/components/building.ngfactory';
import * as import14 from '../../../app/modules/dialog/components/dialog';
import * as import15 from '../modules/dialog/components/dialog.ngfactory';
import * as import16 from '../../../app/modules/shaft/service';
import * as import17 from '../../../app/modules/dialog/service';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.AppComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'main',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent(this.injectorGet(import8.SessionService,this.parentIndex),this.injectorGet(import9.LogService,this.parentIndex));
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('main',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import10.LogComponent>;
  _LogComponent_1_3:import11.Wrapper_LogComponent;
  _text_2:any;
  _el_3:any;
  compView_3:import1.AppView<import12.BuildingComponent>;
  _BuildingComponent_3_3:import13.Wrapper_BuildingComponent;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import14.DialogComponent>;
  _DialogComponent_5_3:import15.Wrapper_DialogComponent;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'aside',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import11.View_LogComponent0(this.viewUtils,this,1,this._el_1);
    this._LogComponent_1_3 = new import11.Wrapper_LogComponent(this.parentView.injectorGet(import9.LogService,this.parentIndex));
    this.compView_1.create(this._LogComponent_1_3.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_3 = new import13.View_BuildingComponent0(this.viewUtils,this,3,this._el_3);
    this._BuildingComponent_3_3 = new import13.Wrapper_BuildingComponent(this.parentView.injectorGet(import16.ShaftService,this.parentIndex));
    this.compView_3.create(this._BuildingComponent_3_3.context);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'dialogs',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import15.View_DialogComponent0(this.viewUtils,this,5,this._el_5);
    this._DialogComponent_5_3 = new import15.Wrapper_DialogComponent(this.parentView.injectorGet(import17.DialogService,this.parentIndex));
    this.compView_5.create(this._DialogComponent_5_3.context);
    this._text_6 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.LogComponent) && (1 === requestNodeIndex))) { return this._LogComponent_1_3.context; }
    if (((token === import12.BuildingComponent) && (3 === requestNodeIndex))) { return this._BuildingComponent_3_3.context; }
    if (((token === import14.DialogComponent) && (5 === requestNodeIndex))) { return this._DialogComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LogComponent_1_3.ngDoCheck(this,this._el_1,throwOnChange);
    this._BuildingComponent_3_3.ngDoCheck(this,this._el_3,throwOnChange);
    this._DialogComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    if (!throwOnChange) { this._DialogComponent_5_3.context.ngAfterContentChecked(); }
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_3.internalDetectChanges(throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this.compView_3.destroy();
    this.compView_5.destroy();
  }
}